env:
  _metadata.config_version: 5.0.4
  _metadata.service_instance_id: "1234 __hostname__"
  flush_interval: 2
  _metadata.configuration_date: 2026-06-13
  _metadata.config_type: fluentbit
  _metadata.blah: blah


service:
  flush: ${flush_interval}
  http_port: 2020
  http_server: on
  log_level: error


pipeline:
  inputs:
    -
      dummy: "{ \"hello\": \"my world\" }"
      name: dummy
      tag: dummy1
    -
      listen: 0.0.0.0
      name: http
      port: 8888
  outputs:
    -
      file: test.txt
      format: out_file
      match: "*"
      name: file
