# server-backed save test
service:
  flush: 1
pipeline:
  inputs:
    - name: forward
      buffer_chunk_size: 1024
      buffer_max_size: 2048
      port: 24224
  outputs:
    - name: null
      match: '*'
